%% generated by soap from: /home/moein/Documents/project/ClubCollect/oqtolib/priv/eboekheouden/soap.xml
%% for service "soapApp" and port "soapAppSoap"
%% using options: [{service,"soapApp"},{port,"soapAppSoap"},{generate,client},{namespaces,[{"http://www.e-boekhouden.nl/soap","eboe"}]},{generate_tests,client},{http_client,soap_client_ibrowse},{client_name,"soap.xml_client"},{strict,true}]

-module(oqtolib_eboe_client).

-include("oqtolib_eboe.hrl").

-export([interface/0]).

%% The functions that are described by the WSDL
-export(['GetAdministraties'/3]).
-export(['GetSaldo'/3]).
-export(['AddFactuur'/3]).
-export(['GetFacturen'/3]).
-export(['AddMutatie'/3]).
-export(['GetMutaties'/3]).
-export(['AddGrootboekrekening'/3]).
-export(['UpdateGrootboekrekening'/3]).
-export(['GetGrootboekrekeningen'/3]).
-export(['AddRelatie'/3]).
-export(['UpdateRelatie'/3]).
-export(['GetRelaties'/3]).
-export(['GetOpenPosten'/3]).
-export(['OpenSession'/3]).
-export(['CloseSession'/3]).
-export(['AutoLogin'/3]).
-export(['GetKostenplaatsen'/3]).
-export(['GetArtikelen'/3]).

-spec 'GetAdministraties'(Soap_body::'eboe:GetAdministraties'(),
  Soap_headers::[soap:soap_header()],
  Options::[any()]) -> soap:soap_response('eboe:GetAdministratiesResponse'()).
'GetAdministraties'(Soap_body, Soap_headers, Options) ->
  soap_client_util:call(Soap_body, Soap_headers, Options, "\"http://www.e-boekhouden.nl/soap/GetAdministraties\"", interface()).

-spec 'GetSaldo'(Soap_body::'eboe:GetSaldo'(),
  Soap_headers::[soap:soap_header()],
  Options::[any()]) -> soap:soap_response('eboe:GetSaldoResponse'()).
'GetSaldo'(Soap_body, Soap_headers, Options) ->
  soap_client_util:call(Soap_body, Soap_headers, Options, "\"http://www.e-boekhouden.nl/soap/GetSaldo\"", interface()).

-spec 'AddFactuur'(Soap_body::'eboe:AddFactuur'(),
  Soap_headers::[soap:soap_header()],
  Options::[any()]) -> soap:soap_response('eboe:AddFactuurResponse'()).
'AddFactuur'(Soap_body, Soap_headers, Options) ->
  soap_client_util:call(Soap_body, Soap_headers, Options, "\"http://www.e-boekhouden.nl/soap/AddFactuur\"", interface()).

-spec 'GetFacturen'(Soap_body::'eboe:GetFacturen'(),
  Soap_headers::[soap:soap_header()],
  Options::[any()]) -> soap:soap_response('eboe:GetFacturenResponse'()).
'GetFacturen'(Soap_body, Soap_headers, Options) ->
  soap_client_util:call(Soap_body, Soap_headers, Options, "\"http://www.e-boekhouden.nl/soap/GetFacturen\"", interface()).

-spec 'AddMutatie'(Soap_body::'eboe:AddMutatie'(),
  Soap_headers::[soap:soap_header()],
  Options::[any()]) -> soap:soap_response('eboe:AddMutatieResponse'()).
'AddMutatie'(Soap_body, Soap_headers, Options) ->
  soap_client_util:call(Soap_body, Soap_headers, Options, "\"http://www.e-boekhouden.nl/soap/AddMutatie\"", interface()).

-spec 'GetMutaties'(Soap_body::'eboe:GetMutaties'(),
  Soap_headers::[soap:soap_header()],
  Options::[any()]) -> soap:soap_response('eboe:GetMutatiesResponse'()).
'GetMutaties'(Soap_body, Soap_headers, Options) ->
  soap_client_util:call(Soap_body, Soap_headers, Options, "\"http://www.e-boekhouden.nl/soap/GetMutaties\"", interface()).

-spec 'AddGrootboekrekening'(Soap_body::'eboe:AddGrootboekrekening'(),
  Soap_headers::[soap:soap_header()],
  Options::[any()]) -> soap:soap_response('eboe:AddGrootboekrekeningResponse'()).
'AddGrootboekrekening'(Soap_body, Soap_headers, Options) ->
  soap_client_util:call(Soap_body, Soap_headers, Options, "\"http://www.e-boekhouden.nl/soap/AddGrootboekrekening\"", interface()).

-spec 'UpdateGrootboekrekening'(Soap_body::'eboe:UpdateGrootboekrekening'(),
  Soap_headers::[soap:soap_header()],
  Options::[any()]) -> soap:soap_response('eboe:UpdateGrootboekrekeningResponse'()).
'UpdateGrootboekrekening'(Soap_body, Soap_headers, Options) ->
  soap_client_util:call(Soap_body, Soap_headers, Options, "\"http://www.e-boekhouden.nl/soap/UpdateGrootboekrekening\"", interface()).

-spec 'GetGrootboekrekeningen'(Soap_body::'eboe:GetGrootboekrekeningen'(),
  Soap_headers::[soap:soap_header()],
  Options::[any()]) -> soap:soap_response('eboe:GetGrootboekrekeningenResponse'()).
'GetGrootboekrekeningen'(Soap_body, Soap_headers, Options) ->
  soap_client_util:call(Soap_body, Soap_headers, Options, "\"http://www.e-boekhouden.nl/soap/GetGrootboekrekeningen\"", interface()).

-spec 'AddRelatie'(Soap_body::'eboe:AddRelatie'(),
  Soap_headers::[soap:soap_header()],
  Options::[any()]) -> soap:soap_response('eboe:AddRelatieResponse'()).
'AddRelatie'(Soap_body, Soap_headers, Options) ->
  soap_client_util:call(Soap_body, Soap_headers, Options, "\"http://www.e-boekhouden.nl/soap/AddRelatie\"", interface()).

-spec 'UpdateRelatie'(Soap_body::'eboe:UpdateRelatie'(),
  Soap_headers::[soap:soap_header()],
  Options::[any()]) -> soap:soap_response('eboe:UpdateRelatieResponse'()).
'UpdateRelatie'(Soap_body, Soap_headers, Options) ->
  soap_client_util:call(Soap_body, Soap_headers, Options, "\"http://www.e-boekhouden.nl/soap/UpdateRelatie\"", interface()).

-spec 'GetRelaties'(Soap_body::'eboe:GetRelaties'(),
  Soap_headers::[soap:soap_header()],
  Options::[any()]) -> soap:soap_response('eboe:GetRelatiesResponse'()).
'GetRelaties'(Soap_body, Soap_headers, Options) ->
  soap_client_util:call(Soap_body, Soap_headers, Options, "\"http://www.e-boekhouden.nl/soap/GetRelaties\"", interface()).

-spec 'GetOpenPosten'(Soap_body::'eboe:GetOpenPosten'(),
  Soap_headers::[soap:soap_header()],
  Options::[any()]) -> soap:soap_response('eboe:GetOpenPostenResponse'()).
'GetOpenPosten'(Soap_body, Soap_headers, Options) ->
  soap_client_util:call(Soap_body, Soap_headers, Options, "\"http://www.e-boekhouden.nl/soap/GetOpenPosten\"", interface()).

-spec 'OpenSession'(Soap_body::'eboe:OpenSession'(),
  Soap_headers::[soap:soap_header()],
  Options::[any()]) -> soap:soap_response('eboe:OpenSessionResponse'()).
'OpenSession'(Soap_body, Soap_headers, Options) ->
  soap_client_util:call(Soap_body, Soap_headers, Options, "\"http://www.e-boekhouden.nl/soap/OpenSession\"", interface()).

-spec 'CloseSession'(Soap_body::'eboe:CloseSession'(),
  Soap_headers::[soap:soap_header()],
  Options::[any()]) -> soap:soap_response('eboe:CloseSessionResponse'()).
'CloseSession'(Soap_body, Soap_headers, Options) ->
  soap_client_util:call(Soap_body, Soap_headers, Options, "\"http://www.e-boekhouden.nl/soap/CloseSession\"", interface()).

-spec 'AutoLogin'(Soap_body::'eboe:AutoLogin'(),
  Soap_headers::[soap:soap_header()],
  Options::[any()]) -> soap:soap_response('eboe:AutoLoginResponse'()).
'AutoLogin'(Soap_body, Soap_headers, Options) ->
  soap_client_util:call(Soap_body, Soap_headers, Options, "\"http://www.e-boekhouden.nl/soap/AutoLogin\"", interface()).

-spec 'GetKostenplaatsen'(Soap_body::'eboe:GetKostenplaatsen'(),
  Soap_headers::[soap:soap_header()],
  Options::[any()]) -> soap:soap_response('eboe:GetKostenplaatsenResponse'()).
'GetKostenplaatsen'(Soap_body, Soap_headers, Options) ->
  soap_client_util:call(Soap_body, Soap_headers, Options, "\"http://www.e-boekhouden.nl/soap/GetKostenplaatsen\"", interface()).

-spec 'GetArtikelen'(Soap_body::'eboe:GetArtikelen'(),
  Soap_headers::[soap:soap_header()],
  Options::[any()]) -> soap:soap_response('eboe:GetArtikelenResponse'()).
'GetArtikelen'(Soap_body, Soap_headers, Options) ->
  soap_client_util:call(Soap_body, Soap_headers, Options, "\"http://www.e-boekhouden.nl/soap/GetArtikelen\"", interface()).

%%% --------------------------------------------------------------------
%%% Internal functions
%%% --------------------------------------------------------------------
interface() ->
    ?INTERFACE.